# 2b2t restart plugin

# Time to where the server will call a restart
Timezone: "America/New_York"
#Time
# 2:00 AM EST
# THIS IS IN 24 HOUR TIME
Hour: 2
Minute: 0
Seconds: 0

string: "&e[SERVER] Server restarting in"
finalstring: "&e[SERVER] Server restarting..."
minutestring: " minutes..."
secondsstring: " seconds..."
secondstring: " second..."